<a href="https://colab.research.google.com/github/kavithachitriki/SCALER_PRACTICE/blob/main/Scaler_Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
a=np.array([[1,2,3],[4 ,5, 6],[7, 8, 9]])

a=np.transpose(a)
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
b=np.flip(a, axis=1)
b

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [16]:
A=np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
b=A+["1"]
print(b)

UFuncTypeError: ignored

In [22]:
def sort_marks(arr2d, j):
    '''Input: arr2d= a 2d python list.
              j= integer representing the number of quiz according to which the marks need to be sorted.
        Output: a 2d numpy array.'''

    # Make sure that you are returning the output matrix simply inside this function.
    
    
    ans = None
    # YOUR CODE GOES HERE
    
    
    return ans

b=np.array([[5,3,9], [2,1,4], [7,6,8]])
print(b)

#b = b[b[:, 2].argsort()]
ans=b[np.argsort(b[:, 1])]
print(ans)

[[5 3 9]
 [2 1 4]
 [7 6 8]]
[[2 1 4]
 [5 3 9]
 [7 6 8]]


In [24]:
import numpy as np
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
X.max(axis=1) = [ 3, 7, 11]


SyntaxError: ignored

In [26]:
X.sum() = 11

SyntaxError: ignored

In [27]:
X.T.max(axis=0) = [ 3, 7, 11]

SyntaxError: ignored

In [29]:
X=[i.min() for i in X] = [0, 4, 8]

SyntaxError: ignored

In [40]:
import numpy as np

def update_height(height,delta):

   height = np.array(height)

   delta = np.array(delta)

   new_height = height+delta 

   return new_height

h=[1,2,3]
d=[1,1,1]
A=update_height(h,d)
print(update_height(h,d))

[2 3 4]


In [41]:
def update_height_p(height, delta):

    new_height=[]

    for i in range(len(height)):

        new_height.append(height[i]+delta[i])

    return new_height

h=[1,2,3]
d=[1,1,1]
B=update_height_p(h,d)
print(update_height_p(h,d))

[2, 3, 4]


In [42]:
B=A

In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10])
x[(x >= -5) & (x <= 15)] *= -1 

In [43]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [44]:
arr1=np.array(['Ram','Astha','Brahat'])
arr2=np.array(['Shyam','Kalyan','Naveen'])
arr1>arr2

array([False, False, False])

In [ ]:
A.shape = (m,)

B.shape = (n, 1)

C.shape = (n, m)

In [48]:
x = np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])