<a href="https://colab.research.google.com/github/kavithachitriki/SCALER_PRACTICE/blob/main/Scaler_Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=[1,2,3,4]


In [7]:
sqr=[num*num for num in a]
sqr

[1, 4, 9, 16]

In [4]:
import numpy as np
b=np.array([1,2,3,4,5])
b


array([1, 2, 3, 4, 5])

In [11]:
type(b)
b**2

array([ 1,  4,  9, 16, 25])

In [12]:
l=range(1000000)

In [13]:
%timeit [i**2 for i in l]

1 loop, best of 5: 304 ms per loop


In [14]:
np_l=np.arange(10000000)

In [16]:
%timeit np_l**2

10 loops, best of 5: 18.7 ms per loop


In [18]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [22]:
arr1**3
arr1

array([1, 2, 3])

In [21]:
arr1.ndim

1

In [23]:
arr1.shape

(3,)

In [24]:
np.arange(1,5,1.5)

array([1. , 2.5, 4. ])

In [28]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
np.linspace(1,1,10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.array([1,4,5,"hi"])

array(['1', '4', '5', 'hi'], dtype='<U21')

In [38]:
np.array([1,2,3,4.5], dtype="int32")

array([1, 2, 3, 4], dtype=int32)

In [52]:
np.array([0,10,100], dtype="object")**10

array([0, 10000000000, 100000000000000000000], dtype=object)

In [1]:
100**10

100000000000000000000

In [5]:
m1=np.array([[1,2,3],[4,5,6]])

In [6]:
m1.shape

(2, 3)

In [7]:
m1.ndim

2

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
len(a)

3

In [12]:
a.shape

(3, 3)

In [13]:
a.ndim

2

In [34]:
m2=np.arange(1,13)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
m2=m2.reshape(4,3)
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
m2.ndim

2

In [33]:
m2.shape

(4, 3)

In [42]:
m2=m2.reshape(1,12)
print(m2)
print(m2.ndim)
print(m2.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2
(1, 12)


In [43]:
m2=np.arange(1,13)
print(m2)
print(m2.ndim)
print(m2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [47]:
m2=np.arange(1,13)
m2=m2.reshape(12,1)
print(m2)
print(m2.shape)
print(m2.ndim)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
(12, 1)
2


In [49]:
a=np.arange(3)
a

array([0, 1, 2])

In [50]:
a.T

array([0, 1, 2])

In [57]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b=a.reshape(12)
print(b)
b.ndim

[ 0  1  2  3  4  5  6  7  8  9 10 11]


1

In [58]:
c=a.flatten()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
d=np.arange(12).reshape(4,3).flatten()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
a=np.arange(12).reshape(3,4)
print(a)
print("after reshape=")
print(a.reshape(-1,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
after reshape=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
a=np.ones((2,3),dtype="int")*5
print(a)
print(a.dtype)

[[5 5 5]
 [5 5 5]]
int64


In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [88]:
np.diag(a)

array([1, 2, 3])

In [89]:
m1=np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
m1[12]

IndexError: ignored

In [94]:
m2=np.arange(1,10).reshape(3,3)
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
m2[1][2]

6

In [96]:
m2[1,2]

6

In [97]:
m2[1,-1]

6

In [98]:
m1=np.array([100,200,300,400,500,600])

In [99]:
m1[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [100]:
m1=np.arange(9).reshape(3,3)
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
m1[[0,1,2],[0,1,2]]

array([0, 4, 8])

In [102]:
m1=np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
m1[:5]

array([0, 1, 2, 3, 4])

In [105]:
m1=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
m1[0,1:3]

array([1, 2])

In [107]:
m1[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
m1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [117]:
m1[:,(1,3)]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [118]:
a=np.array([0,1,2,3,4,5])
a[4:]=10
a

array([ 0,  1,  2,  3, 10, 10])

In [126]:

a=np.array([1,2,3,4,5])
b=np.array([8,7,6])

In [127]:
a[2:]=b[::-1]
a

array([1, 2, 6, 7, 8])

In [122]:
a[2:]

array([], shape=(0, 5), dtype=int64)

In [130]:
m1=np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
m1<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [132]:
m1[m1<6]

array([0, 1, 2, 3, 4, 5])

In [138]:
m1[(m1%2) == 0 & (m1%5 ==0)]

array([ 0,  2,  4,  6,  8, 10])

In [140]:
a=np.array([0,1,2,3,4,5])
mask=(a%2 == 0)
print(mask)
a[mask]=-1
a

[ True False  True False  True False]


array([-1,  1, -1,  3, -1,  5])

In [142]:
np.array([1.2,3.4,5.1],dtype="int32")

array([1, 3, 5], dtype=int32)

In [148]:
import math


a=np.array([0,1,2,3,4,5])
sigmoid=1/(1 + np.exp(-a))
print(np.round(sigmoid,2))



[0.5  0.73 0.88 0.95 0.98 0.99]


In [155]:
import numpy as np
def seq(start, length, step):
  arr=np.array([])
  for i in range(0,length):
    arr=np.insert(arr,i,(start+i*step)).astype("int32")
  return arr

print(seq(5,10,3))

[ 5  8 11 14 17 20 23 26 29 32]


In [162]:
def new_mat(mat):
  mat=mat[mat%2 == 0]
  print(mat)
  size=1
  print("length=",len(mat))
  for i in range(len(mat)-1,1,-1):
    print(i)
    if len(mat) % i == 0:
      size=i
      print("size=",size)
      break


  return mat.reshape(size,size)

matrix=np.array([[1,1,2],[4,6,8]])
print(new_mat(matrix))

[2 4 6 8]
length= 4
3
2
size= 2
[[2 4]
 [6 8]]
