<a href="https://colab.research.google.com/github/kavithachitriki/SCALER_PRACTICE/blob/main/Scaler_Practice_24Jun2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
input = np.array([3 ,4 ,6 ,8 ,2 ,5])
x = np.array(input, dtype="b")

x

b=np.vectorize(np.binary_repr)(x, 8)
print(b)
c=np.array(b,dtype="int")
c

['00000011' '00000100' '00000110' '00001000' '00000010' '00000101']


array([  11,  100,  110, 1000,   10,  101])

In [ ]:
x

array([[2, 3, 4],
       [5, 6, 7]], dtype=int8)

In [13]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [7]:
b=np.sum(a,axis=1)
b.shape

(3,)

In [10]:
np.mean(a,axis=1)

array([1.5, 5.5, 9.5])

In [16]:
np.min(a,axis=1)

array([0, 4, 8])

In [22]:
np.max(a,axis=None)

11

In [20]:
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [23]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])

In [24]:
a<=b

array([ True,  True, False, False])

In [25]:
np.any(a<=b)

True

In [26]:
np.all(a<=b)

False

In [27]:
np.sum(a<=b) == len(a)

False

In [28]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])


In [29]:
np.all((a<=b) & (b<=c))

True

In [30]:
a=np.array([2,30,41,7,17,52])
np.sort(a)

array([ 2,  7, 17, 30, 41, 52])

In [31]:
a

array([ 2, 30, 41,  7, 17, 52])

In [32]:
np.argsort(a)

array([0, 3, 4, 1, 2, 5])

In [33]:
m=np.array([[23,4,43],[12,89,3],[69,420,0]])

In [34]:
m

array([[ 23,   4,  43],
       [ 12,  89,   3],
       [ 69, 420,   0]])

In [36]:
np.sort(m)

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [37]:
!gdown 1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF

Downloading...
From: https://drive.google.com/uc?id=1kXqcJo4YzmwF1G2BPoA17CI49TZVHANF
To: /content/fitness.txt
100% 3.14k/3.14k [00:00<00:00, 9.28MB/s]


In [55]:
data=np.loadtxt("fitness.txt",dtype="str")

In [42]:
type(data)

numpy.ndarray

In [43]:
data.shape

(96, 7)

In [60]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [46]:
data[0:5,:]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

In [48]:
data[0,:]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [49]:
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [50]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [53]:
data.T[:2]

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [56]:
date,step_count=data.T[:2]

In [57]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [58]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [61]:
date,	step_count,	mood,	calories_burned,	hours_of_sleep,	bool_of_active,	weight_kg = data.T

In [63]:
weight_kg

array(['66', '66', '66', '66', '66', '66', '66', '66', '66', '65', '65',
       '65', '65', '65', '65', '65', '65', '65', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64'], dtype='<U10')

In [68]:
step_count=np.array(step_count,dtype="int")
step_count.dtype

dtype('int64')

In [69]:
hours_of_sleep=np.array(hours_of_sleep,dtype="int")
weight_kg=np.array(weight_kg,dtype="float")

In [70]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [72]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [73]:
mood[mood=="300"]="Happy"

In [74]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', 'Happy', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', 'Happy', '200', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', '200', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200', '100',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       '100', '200', '200', '100', '100', '200', '200', 'Happy', '200',
       '200', '100', '200', '100', '200', '200', '100', '100', '100',
       '100', 'Happy', '200', 'Happy', '200', '100', '100', '100', '200',
       '200', '100', '100', 'Happy', '200', '200', 'Happy'], dtype='<U10')

In [77]:
mood=="200"

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True, False,  True,  True, False, False, False, False,
       False,  True, False,  True, False, False, False,  True,  True,
       False, False, False,  True,  True, False])

In [78]:
mood[mood=="200"]="Neutral"

In [79]:
mood

array(['Neutral', '100', '100', '100', 'Neutral', '100', '100', '100',
       '100', '100', '100', '100', 'Happy', '100', '100', '100', '100',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', '100', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', '100', 'Neutral', 'Neutral',
       '100', '100', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       '100', 'Neutral', '100', 'Neutral', 'Neutral', '100', '100', '100',
       '100', 'Happy', 'Neutral', 'Happy', 'Neutral', '100', '100', '100',
       'Neutral', 'Neutral', '100', '100', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [80]:
mood=="100"

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [81]:
mood[mood=="100"]="Sad"

In [82]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [87]:
np.unique(bool_of_active)

array(['0', '500'], dtype='<U10')

In [88]:
bool_of_active[bool_of_active=='0']='Inactive'
bool_of_active[bool_of_active=='500']='Ative'

In [89]:
bool_of_active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Ative',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Ative', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Ative', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Ative',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Ative', 'Ative', 'Ative', 'Ative', 'Ative', 'Ative', 'Ative',
       'Ative', 'Ative', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Ative', 'Ative', 'Ative', 'Ative',
       'Ative', 'Ative', 'Ative', 'Ative', 'Ative', 'Ative', 'Ative',
       'Ative', 'Inactive', 'Ative', 'Ative', 'Inactive', 'Ative',
       'Ative', 'Ative', 'Ative', 'Ative', 'Inactive', 'Ative', 'Ative',
       'Ative', 'Ative', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Ative', 'Ative', 'Ative', 'Ati

In [90]:
step_count.mean()

2935.9375

In [91]:
np.argsort(step_count)

array([ 2, 86,  8, 91, 92, 85, 16, 21, 74, 44, 22, 87, 23, 70, 51, 93, 80,
       30, 50, 43, 37, 78, 90, 42, 79, 56, 66, 52, 53,  7, 71,  9, 57, 88,
       14, 65, 72, 28, 61, 94, 95, 24, 29, 63, 89, 59, 15, 64, 84, 10, 38,
       17, 13, 76, 55, 62, 19, 68, 39, 35, 20, 77, 58, 33, 82, 41, 45,  6,
       18, 47, 26,  5, 25, 34, 11, 12, 27, 40, 73, 49, 83,  3, 31,  0, 81,
       60, 46,  1, 32, 36, 75, 54,  4, 48, 67, 69])

In [97]:
arr=np.argsort(step_count)
date[arr[len(arr)-1]]

'14-12-2017'

In [98]:
np.argmax(step_count)

69

In [100]:
date[np.argmin(step_count)]

'08-10-2017'

In [101]:
np.sum(mood=="Happy")

40

In [102]:
np.sum(mood=="Sad")

29

In [103]:
np.sum(mood=="Neutral")

27

In [105]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))